### ISSUE TITLE
Disconnection on opening inventory in creative mode

### ISSUE THREAD

**Issue by KrazyMiner001** [enjarai/trickster#1]
Opening your inventory while in creative mode if you have a scroll or other spell containing item which has an inner circle, the game disconnects you for "Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packe 'serverbound/minecraft:set_creative_mode_slot"

### Steps to reproduce: 
1. Get a scroll item
2. Do the inner revision spell
3. Be in creative mode
4. Open inventory

**Comment by enjarai** [comment]
Fixed in 1.0.3. Thanks for reporting.
