### ISSUE TITLE
Game crashes when singleplayer world has finished loading (Similar to #3)

### ISSUE THREAD

**Issue by ZannCoelz** [enjarai/trickster#21]
Is this also an issue with owo-lib like #3? It has some similarities, but instead happens when a singleplayer world has finished loading. I didn't know which place to report this to so I decided to ask here. I can also go report it to owo-lib if the issue is theirs.

Here's the crashreport:
[crash-2024-07-19_13.02.52-server.txt](https://github.com/user-attachments/files/16310790/crash-2024-07-19_13.02.52-server.txt)

**Comment by StellarWitch7** [comment]
As @enjarai said in #3.
