### ISSUE TITLE
Erroneous translations strings as of 2.0.0-beta.3

### ISSUE THREAD

**Issue by Ch1216** [enjarai/trickster#25]
Undefined Spell Strings:
trickster.trick.trickster.polymorph (Polymorph Ploy)
trickster.trick.trickster.dispel_polymorph (Dispel Polymorph Ploy)
trickster.trick.trickster.raycast_entity (Scout's Distortion)
trickster.trick.trickster.raycast_side (Architect's Distortion)

Note: Archer's Distortion erroneously defined as Scout's Distortion

Other Undefined Strings:
death.attack.mana_overflux.player

#23 fixes all the spell string mistakes but not the death due to mana overflux shortly after being punched by another entity string

**Comment by StellarWitch7** [comment]
I noticed the first four in #24 and did fix them in #23.

**Comment by StellarWitch7** [comment]
Regarding `death.attack.mana_overflux.player`, I've just pushed a commit to #23 that should "fix" this issue -- I simply copied the same string for it. We'll look into giving it a unique string later, but at the very least there'll be one, if we forget.

**Comment by Ch1216** [comment]
Nice, but so you know `.entity` death messages are not a thing, `.player` appears even if it a mob that attacked the player beforehand
Heres also a suggestion: what about "<attacker> ruined <victim>'s magic show"

**Comment by StellarWitch7** [comment]
> Nice, but so you know `.entity` death messages are not a thing [...]

Mojang, why?

Thanks for the tip and the suggestion!
