### ISSUE TITLE
Erroneous translations strings as of 2.0.0-alpha.4

### ISSUE THREAD

**Issue by Ch1216** [enjarai/trickster#26]
death.attack.mana_overflux.player is not defined properly and instead of showing the names for who attacked and who died, it shows the variables
![variablebevariainting](https://github.com/user-attachments/assets/569f90d8-795d-4af6-91ce-037d51468642)

item.trickster.written_scroll is not defined, it shows up when doing a Juggling Delusion while holding a written scrooll on the other hand

**Comment by enjarai** [comment]
Damn still? I'll fix it.

**Comment by Ch1216** [comment]
Fixed in 2.0.0-alpha.5
