### ISSUE TITLE
Game crashes when opening Top Hat (while having other mods)

### ISSUE THREAD

**Issue by ZannCoelz** [enjarai/trickster#3]
I'm building a modpack and was testing if Trickster would work in it but when I open the Top Hat item my game crashes. I tried it without any other mods and the crash didn't happen so it's probably a conflict but I couldn't figure out what caused it.

Here is the crash report:
[crash-2024-06-26_19.41.41-server.txt](https://github.com/user-attachments/files/15992693/crash-2024-06-26_19.41.41-server.txt)

**Comment by enjarai** [comment]
This seems to be an issue in owo-lib. I've contacted its dev about this, and I expect she'll be looking into it.

**Comment by enjarai** [comment]
Is this issue fixed on th latest version? I can't recreate it anymore.

**Comment by enjarai** [comment]
Stale, and probably no longer relevant.
