### ISSUE TITLE
If you use a Noutlist's Ploy on a Scroll and Quill it can't be opened until you write something else to it.

### ISSUE THREAD

**Issue by julian428** [enjarai/trickster#49]
[Screencast from 2024-09-12 16-37-33.webm](https://github.com/user-attachments/assets/26fe4db6-a5e8-43cd-affc-6bfc88caa950)

You can't see it on the recording but I am trying to open the scroll, right clicking it.

**Comment by StellarWitch7** [comment]
This is a known issue, though I've yet to look into its cause.

**Comment by StellarWitch7** [comment]
Fixed in commit https://github.com/enjarai/trickster/commit/b0bc63bf94b29d17c216e6743e641d431c1d3821.
