### ISSUE TITLE
Cannot access/see Notulist's Ploy.

### ISSUE THREAD

**Issue by KenanTheFab** [enjarai/trickster#53]
Hovering over the "link" in the book makes a popup stating "Invalid Interal Link: ^trickster:ploys/basic#4" appear rather than the ability to click on  it and view the symbol.

**Comment by StellarWitch7** [comment]
This was a known issue, though I'd forgotten about it. Just patched it with https://github.com/enjarai/trickster/commit/942f2cf83abff0e925fde4507ce39d71d05896e8. Thanks.
