### ISSUE TITLE
Mirror is replacing the current spell that is beeing drawn with a old one that was cleared from it.

### ISSUE THREAD

**Issue by julian428** [enjarai/trickster#54]
[Screencast from 2024-09-16 21-07-23.webm](https://github.com/user-attachments/assets/35c5369e-b137-4e8b-a601-b2a5f8cfe4d6)

**Comment by StellarWitch7** [comment]
Are you on the latest (2.0.0-alpha.34) version?

**Comment by StellarWitch7** [comment]
2.0.0-alpha.34 includes some significant changes to the way the mirror reloads the UI's spell. I tested it quite a bit, but it's not surprising that something was missed, given the extent of the changes.

**Comment by julian428** [comment]
I am on .34

**Comment by StellarWitch7** [comment]
Alright. I'll see what I can do.

**Comment by StellarWitch7** [comment]
Fixed by https://github.com/enjarai/trickster/commit/e3f894d2232ab40de685580dd6d0b32573ef6b6e, thanks for opening an issue.
