### ISSUE TITLE
The Scroll and Quill doesn't save the new state

### ISSUE THREAD

**Issue by julian428** [enjarai/trickster#55]
[Screencast from 2024-09-16 22-36-48.webm](https://github.com/user-attachments/assets/5d0b730a-6367-48fb-b0c5-639284567e53)
When I export the spell, the spell that is exported is the old one. Also for other players the spell contains the old version of the spell. I have tested it both on single and multiplayer.
![image](https://github.com/user-attachments/assets/d4509775-be10-4e9e-89ca-e1fd30764e39)
![image](https://github.com/user-attachments/assets/49aee03c-861d-4fe0-b407-02e0205720c6)

**Comment by StellarWitch7** [comment]
This is the same issue as #54, I'm looking into it.
