### ISSUE TITLE
Warrior's rage works only on inanimate entities.

### ISSUE THREAD

**Issue by julian428** [enjarai/trickster#56]
https://github.com/user-attachments/assets/d1b03352-1d75-4a17-aae7-d25ed58991ca

![Screenshot from 2024-09-17 12-44-41](https://github.com/user-attachments/assets/6787d91c-6d64-40a0-943b-ad624570d864)

### Spell export:
`YwyT9+ZnamJYyARiMDAwMTCAGIwu7AzMIMaiBiYGJvf5ViccGKAAN4cI9QD0B61abwAAAA==`

**Comment by StellarWitch7** [comment]
In this video, you apply velocity on the tick just before the entity is hit. The attack logic then inflicts knockback, cancelling the velocity. This is expected behaviour.
