### ISSUE TITLE
I die from mana overuse in creative mode

### ISSUE THREAD

**Issue by julian428** [enjarai/trickster#59]
**Describe the bug**
When I use too much mana in creative I die.

**To reproduce**
Steps to reproduce the behaviour:
1. use a lot of mana, above 240 without a battery ( i tried to place a spell ) in creative mode
2. die

**Expected behaviour**
Before the .37 update I just lived and the spell was placed

**Attachments**
[Screencast from 2024-09-23 17-21-23.webm](https://github.com/user-attachments/assets/28852e61-7927-4802-8737-7fd45c432abd)

**Comment by StellarWitch7** [comment]
This will be fixed in version 2.0.0-alpha.38.
