### ISSUE TITLE
ManaEventType Registry uses the same RegistryKey as ManaHandlerType Registry

### ISSUE THREAD

**Issue by unilock** [enjarai/trickster#66]
https://github.com/enjarai/trickster/blob/d4b000e46bbfe20b1976c4c3fe07e9d0c381d81e/src/main/java/dev/enjarai/trickster/spell/mana/generation/event/ManaEventType.java#L10

This causes a crash on NeoForge - I guess it's more strict than Fabric about these things :p

**Comment by StellarWitch7** [comment]
I suppose good sleep does benefit code quality... I'll fix this up before the next version. Thanks for the issue!
